/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DecorationType = IDL.Variant({
  'Flower' : IDL.Null,
  'Balloon' : IDL.Null,
});
export const Category = IDL.Variant({
  'Birthday' : IDL.Null,
  'Marriage' : IDL.Null,
  'Funeral' : IDL.Null,
});
export const DecorationItem = IDL.Record({
  'id' : IDL.Nat,
  'typ' : DecorationType,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllItems' : IDL.Func([], [IDL.Vec(DecorationItem)], ['query']),
  'getItem' : IDL.Func([IDL.Nat], [DecorationItem], ['query']),
  'getItemsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(DecorationItem)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DecorationType = IDL.Variant({
    'Flower' : IDL.Null,
    'Balloon' : IDL.Null,
  });
  const Category = IDL.Variant({
    'Birthday' : IDL.Null,
    'Marriage' : IDL.Null,
    'Funeral' : IDL.Null,
  });
  const DecorationItem = IDL.Record({
    'id' : IDL.Nat,
    'typ' : DecorationType,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllItems' : IDL.Func([], [IDL.Vec(DecorationItem)], ['query']),
    'getItem' : IDL.Func([IDL.Nat], [DecorationItem], ['query']),
    'getItemsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(DecorationItem)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };