/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Birthday' : null } |
  { 'Marriage' : null } |
  { 'Funeral' : null };
export interface DecorationItem {
  'id' : bigint,
  'typ' : DecorationType,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
}
export type DecorationType = { 'Flower' : null } |
  { 'Balloon' : null };
export interface _SERVICE {
  'getAllItems' : ActorMethod<[], Array<DecorationItem>>,
  'getItem' : ActorMethod<[bigint], DecorationItem>,
  'getItemsByCategory' : ActorMethod<[Category], Array<DecorationItem>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];